@echo off
echo  Subindo PostgreSQL...
docker-compose up -d
timeout /t 5 /nobreak > nul
echo  Configurando banco e carregando dados...
python src/setup_database.py
echo  Iniciando dashboard...
python -m streamlit run src/dashboard.py